### ISSUE TITLE
Error with "barcodes file does not appear to exist" when run DropletQC

### ISSUE THREAD

**Issue by RuiqiaoHe** [powellgenomicslab/DropletQC#1]
I have installed DropletQC in my Linux server where the R version is "R version 4.1.1 (2021-08-10)". However, it failed for some reasons as below, when I ran on my own dataset:
 
![image](https://user-images.githubusercontent.com/34981680/144600821-9d80f1d8-faae-4dd3-aaee-906a2de2acbe.png)
But, my barcode file exist:
![image](https://user-images.githubusercontent.com/34981680/144600945-a886a55c-4edb-4495-bf93-18bb274cba37.png)
Could you please help me with the problem?

**Comment by WalterMuskovic** [comment]
Hi @RuiqiaoHe sorry for the delayed reply. From the above code it looks like you've adapted the example code in the documentation for the `nuclear_fraction_annotation` function which uses these small test files I created; 

1. chr1.gff3 - small gene annotation file I made for testing this function
2. possorted_genome_bam.bam - small BAM with 100,000 simulated reads
3. barcodes.tsv.gz - compressed text file with 100 cell barcodes

and this code:

`nf3 <- nuclear_fraction_annotation(
annotation_path = system.file("extdata/outs/chr1.gff3", package = "DropletQC"),
bam = system.file("extdata/outs/possorted_genome_bam.bam", package = "DropletQC"),
 barcodes = system.file("extdata/outs/filtered_feature_bc_matrix/barcodes.tsv.gz", package = "DropletQC"),
 tiles = 1, cores = 1, verbose = FALSE)`

Those three files live [here](https://github.com/powellgenomicslab/DropletQC/tree/main/inst/extdata/outs) and get downloaded when you install the R package. We use them by creating a path to them with
`system.file("path/to/file", package = "DropletQC")`. It looks like you'd like to use your own files, in which case you can just provide paths to them directly like this:

`nf3 <- nuclear_fraction_annotation(
annotation_path = "fracdata/outs/genes.gtf",
bam = "fracdata/outs/possorted_genome_bam.bam",
barcodes = "fracdata/outs/filtered_feature_bc_matrix/barcodes.tsv.gz")`

Would you mind to try the above and see if that addresses your problem? 

Also, if you have 10x data and want to use the existing intron/exon tags in your bam file, you could try just using;
`nf3 <- nuclear_fraction_tags(outs =  "fracdata/outs")`

**Comment by RuiqiaoHe** [comment]
Thank you for the kindly reply. I have successfully run the code that provided above. However, there are a lot of 'NaN' in the output, up to ~37% (see the picture below).

 <img width="350" height="200" src="https://user-images.githubusercontent.com/34981680/145552893-a29aee47-b0d7-479c-8158-dc54aecbf55c.png"/>

Could you please kindly explain the meaning of the 'NaN' in the output? Is there something wrong with my operation?

**Comment by WalterMuskovic** [comment]
Ho @RuiqiaoHe , glad to hear the `nuclear_fraction_annotation` function is working for you now. The NaNs indicate that no reads were found overlapping exon or intron regions for those cell barcodes in your bam file. Your other cell barcodes seem to have a very low number of reads detected too. Do you mind to check that the gene annotation you're using (genes.gtf) has chromosome names that match your bam file e.g. by running
`grep '^[^#;]' genes.gtf | cut -f1 | uniq`
to see what chromosomes are in your annotation, and 
`samtools view -H possorted_genome_bam.bam | grep "^@SQ"`
to see what the chromosome names are in your BAM file? If you run `nuclear_fraction_tags` with `verbose=TRUE` it should spit out a warning about it as well - if they don't match. My first guess is that you might have a mix of UCSC & NCBI chromosome names e.g. "chr1" vs "1".

**Comment by RuiqiaoHe** [comment]
This is the output when I run the code for my genes.gtf:
<img width="200" height="400" src="https://user-images.githubusercontent.com/34981680/145998164-342e3b70-bb67-46a1-b48c-00c76224c42b.png" />
This is the output of the chromosome names in my BAM file:
<img width="320" height="400" src="https://user-images.githubusercontent.com/34981680/145998398-7cde0bc7-0dfb-4971-9bd5-dcee0d106cc1.png" />
Is there anything wrong with my files? I am not quite familiar with this. Thanks a lot!

**Comment by WalterMuskovic** [comment]
Hi @RuiqiaoHe,

No that all looks fine. There are a few other things I can think that could cause behaviour like this, but it might be quicker if we try another method first. There are two functions in the package for calculating the nuclear fraction; `nuclear_fraction_annotation` and `nuclear_fraction_tags`. The function `nuclear_fraction_tags` just uses the 'RE' tags that are already in [bam files produced by cellranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam) to assign reads as exon/intronic. Are you able to try run this:
`nf3 <- nuclear_fraction_tags(outs = "fracdata/outs")` 
and see if you get the same issue with lots of NA's?
Would you mind to also report how many barcodes you have (`dim(nf3)`)?

**Comment by WalterMuskovic** [comment]
Hi @RuiqiaoHe, I haven't heard from you so going to assume that you're no longer having this issue. Please reach out if you are or need a hand with anything.

**Comment by RuiqiaoHe** [comment]
Thanks a lot for your kind help.
