### ISSUE TITLE
DropletQC and DecontX

### ISSUE THREAD

**Issue by xie186** [powellgenomicslab/DropletQC#2]
Hi, Thank you for developing DropletQC. Based on the manuscript of DropletQC, there are three types of droplets: “empty droplets", "droplets containing damaged cells" and "intact droplets". But based on the manuscript of DecontX, ambient RNA can incorporate into intact droplets. My questions is what you suggestion is on how to use DropletQC and DecontX? Should we first use DropletQC and then DecontX? Or the other way around? Or just DropletQC is fine? Thanks.

**Comment by WalterMuskovic** [comment]
Hi Shaojun,

Hope all's well and sorry for the delay getting back to you, I was on leave the last few weeks. DropletQC can be used to flag cell-free droplets and droplets that may contain damaged cells. But the remaining droplets containing intact cells will, as you point out, usually be contaminated with some degree of ambient RNA. I've been working with dissociated brain tissue samples which can sometimes be heavily contaminated with ambient RNA -  our original motivation for developing the package.

Unfortunately I don't have any experience with DecontX, but if I understand correctly you want to remove the contribution of the contaminating ambient RNA from the expression matrix of your intact cells? If that's the case I've found the [CellBender](https://github.com/broadinstitute/CellBender) software's [remove-background](https://cellbender.readthedocs.io/en/latest/getting_started/remove_background/index.html) tool to be very useful for that. You could try using DropletQC to identify your intact cells and then looking at the adjusted counts output by `remove-background` for those cells.

Let me know if I can help with anything  - or if I completely misunderstood your question!

**Comment by xie186** [comment]
Hi @WalterMuskovic, thank you so much for your response. I  really appreciate it. Currently I'm using DropletQC to identify `empty droplet`. Then I use [DecontX](https://www.bioconductor.org/packages/release/bioc/vignettes/celda/inst/doc/decontX.html#running-decontx) to remove the contribution of the contaminating ambient RNA. DecontX can utilize `empty droplet` to empirically estimate the distribution of ambient RNA. I'll also check [CellBender](https://github.com/broadinstitute/CellBender). Thanks again.
