### ISSUE TITLE
Can I use DropletQC after manual filtering of droplets with low UMIs/features, high % mito etc.?

### ISSUE THREAD

**Issue by lucygarner** [powellgenomicslab/DropletQC#5]
Hi,

I have used Cell Ranger count (with underlying `EmptyDrops`) and then performed manual filtering for cells with low UMI/gene counts and/or high % mitochondrial reads. Can I use `DropletQC` after this or would this interfere with the nuclear fraction distributions and therefore influence the output of `DropletQC`?

Best wishes,
Lucy

**Comment by WalterMuskovic** [comment]
Hi Lucy,

Hope all's well. Yes you can do it that way, but I'd recommend running DropletQC before any other filtering on MT% or UMIs. As you say, it will help to have the full distributions of the UMI counts and nuclear fraction values. These functions;
`identify_empty_drops()` and `identify_damaged_cells()` will work better with all droplets included.

Cheers,
Walt
