### ISSUE TITLE
seqids cannot be found in the provided annotation

### ISSUE THREAD

**Issue by mdmanurung** [powellgenomicslab/DropletQC#6]
Hi, I encountered this warning message after running `nuclear_fraction_annotation`:

```
Warning message:
The following seqids; *,GL000008.2,GL000208.1,GL000214.1,GL000216.2,GL000220.1...KI270752.1,KI270753.1,KI270754.1,KI270755.1,KI270756.1,KI270757.1 are present in the provided BAM file but cannot be found in the provided annotation. 
```
I have made sure that I used the same .gtf file from refgenome build that was used for cellranger.

What does this warning mean? Should I proceed?

Thanks for your time.

**Comment by WalterMuskovic** [comment]
Hi @mdmanurung,

Hope all's well. You can safely ignore the warning and proceed. 

It's not a big problem if the scaffold and contigs are different, as long as you don't have a situation where the main chromosome names are mismatched e.g. the BAM file seqids are GENCODE/UCSC "chr1" and the gtf are Ensembl "1". 

Cheers,
Walt

**Comment by mdmanurung** [comment]
Thank you for the clarification!
