### ISSUE TITLE
No empty drop or many empty drops?

### ISSUE THREAD

**Issue by s2hui** [powellgenomicslab/DropletQC#7]
Hello,

I have just started using DropletQC and have found it helpful for identifying empty and damaged drops/cells in my data set.  However, I have come across some odd plots when running identify_empty_droplets(..include_plot = TRUE)) and wondered how to interpret them (see figure below).

<img width="908" alt="image" src="https://user-images.githubusercontent.com/10944134/217096563-a12f4337-f299-4500-8b38-af9ce15265b9.png">

Specifically, I don't see a bimodal density distribution (ie an obvious group of empty cells).  Does this mean I don't have any empty droplets or that most of my "cells" are empty (ie. there does look like there maybe a faint separation of two clusters around nf = 0.25).

I ran DropletUtils::emptyDrops() and it does predict empty drops in my data set so maybe it is the latter?

This is the code I used (simplified):
```
bam = BAM_FILE_NAME
bam_index= BAM_INDEX_NAME
barcodes = "barcodes.tsv.gz"
10X_out_path = PATH_TO_10X_OUTPUT

nf2 <- nuclear_fraction_tags(
   bam = bam,
   bam_index = bam_index,
   barcodes = barcodes,
   tiles = 1,
   cores = 1,
   verbose = FALSE
)

so <- CreateSeuratObject(10X_out_path)
df_nf_umi = data.frame(nf = nf2$nuclear_fraction, umi = so$nCounts_RNA)

res_empty_drops <- identify_empty_drops(nf_umi=df_nf_umi,plot_path=OUT_DIR,include_plot=T,plot_name="Plot_out.pdf",pdf_png="pdf")
```

Thanks for your insight, 
@s2hui

**Comment by WalterMuskovic** [comment]
Hi @s2hui glad to hear you've been finding DropletQC useful. It could be that your dataset doesn't have many empty droplets. It doesn't look like it from the plot (the lower panel above), but there's some overplotting of the low nuclear fraction droplets. You might have a population of damaged cells - the high nuclear fraction droplets off to the right. Could you look at the mitochondrial gene content of those droplets?

```
library(tidyverse)
library(Seurat)

# Plot with droplets coloured by the percentage of reads that map to the
# mitochondrial genome
so[["percent.mt"]] <- PercentageFeatureSet(so, pattern = "^MT-")
df_nf_umi <- mutate(df_nf_umi, percent.mt = so$percent.mt) %>%
    ggplot(aes(x=nf, y=log10(umi), colour=percent.mt)) +
    geom_point() +
    scale_color_viridis_c(option="magma")
```
and plot the low nuclear fraction droplets with smaller points and lower opacity? 
```
# Plot (low nf) droplets with low nuclear fraction
ggplot(df_nf_umi, aes(x=nf, y=log10(umi))) +
    scale_color_viridis_c(option="magma") +
    geom_point(size=0.2, alpha=0.3) +
    xlim(c(0,0.25))
```

hopefully that will give some more clues

**Comment by s2hui** [comment]
Thanks for the quick and helpful reply!
I made the two plots as you suggested and they look as follows:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/10944134/217270102-c3a167e4-1227-4eef-a205-3d27240c7312.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/10944134/217270184-64203047-7b40-4019-82b2-79d452a7adc2.png">

Plotting it this way, it is clearer that there does seem to be a small cluster of empty cells (First plot, bottom left, right below the population of cells) and another clear population of damaged cells to the right.  The empty and damaged cells have more cells with MT higher content in them as well compared to the cluster of cells.  Since the empty cluster is right below the cluster of cells, this would explain why I don't see a bimodal distribution.

Is my understanding correct?  Thanks again!
@s2hui

**Comment by WalterMuskovic** [comment]
Hi @s2hui. Yes that's how I would interpret it as well.

**Comment by s2hui** [comment]
Thanks alot for your help!
